disabled_rules: # rule identifiers to exclude from running
  # - type_name
opt_in_rules: # some rules are only opt-in
  # Find all the available rules by running:
  # swiftlint rules
whitelist_rules:
  - trailing_newline
  # - weak_delegate
  # - trailing_whitespace
included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - GrowingUp/Supporting Files/R.generated.swift
  - Carthage
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)