default_platform :ios
fastlane_require 'dotenv'

platform :ios do

	# Public

  lane :app_store do
    ensure_git_status_clean
    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_filepath: ENV['ASC_KEY_PATH']
    )
    match(
      type: "appstore",
      readonly: false,
      api_key: api_key,
      app_identifier: ["pro.ziganshin.GrowingUp", "pro.ziganshin.GrowingUp.Widget"]
    )
    version_number = get_version_number(target: "GrowingUp")
    build_number = increment_build_number
    complete_version_number = version_string(version_number, build_number)
    change_log = change_log_since_last_tag
    gym(
      scheme: "GrowingUp",
      export_method: "app-store"
    )
    pilot(
      api_key: api_key,
      changelog: change_log,
      beta_app_feedback_email: "zigdanis@gmail.com"
    )
    commit_version_bump(
      force: true,
      xcodeproj: "GrowingUp.xcodeproj",
      message: "Version Bump to #{complete_version_number}")
    push_to_git_remote
    clean_build_artifacts
  end

  def change_log_since_last_tag
    return changelog_from_git_commits(
      pretty: '- %s',
      merge_commit_filtering: "exclude_merges"
    )
  end

  def version_string(version_number, build_number)
    "#{version_number} (#{build_number})"
  end

  def version_tag(version_number, build_number)
    "#{version_number}.#{build_number}"
  end
end
